### ISSUE TITLE
`call` vs `apply`. And what about `bind`?

### ISSUE THREAD

**Issue by alvaropinot** [lbdjs/sessions#1]
# Interesting links

* [MDN: call](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/call)
* [MDN: apply](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply)
* [MDN: bind](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind)

* https://passy.svbtle.com/partial-application-in-javascript-using-bind

**Comment by leireNN** [comment]
```js
function sum (a, b) {
    console.log(this)
    return this.total + a + b
}

var order = {
    total:20
}
var taxes = 2

var sumOrder = sum.bind(order)
console.log(sumOrder)

sumOrder(3,2)

sum.bind(order)(2,3)

var sumOrderPlusTaxes = sum.bind(order, taxes)
sumOrderPlusTaxes(50)

sum.bind(null, 2)(5)
```

**Comment by alvaropinot** [comment]
# Partial Application with `bind()`

```js
function sum (a, b) {
  return a + b
}
```

`bind` will return a function with the first argument fixed as `2` or aka partially applied.

```js
// the first argument, the newly desired `this` value/context can be ignored as we are not dealing with any `this` context.
const addTwo = sum.bind(null, 2)
```


now you can use `addTwo` as many times as you want.
```js
addTwo(5) // 7
addTwo(2) // 4
```
