### ISSUE TITLE
Closures🍆

### ISSUE THREAD

**Issue by lluissuros** [lbdjs/sessions#2]

**Comment by alvaropinot** [comment]
there is this great article from @ericelliott as part of the **Master the JavasScript interview** series

https://medium.com/javascript-scene/master-the-javascript-interview-what-is-a-closure-b2f0d2152b36

**Comment by juliomatcom** [comment]
Hello,
A good starting point into Closures is  [You-Dont-Know-JS#closure](https://github.com/getify/You-Dont-Know-JS/blob/master/up%20%26%20going/ch2.md#closure) 
Next you can go further with [scope & closures](https://github.com/getify/You-Dont-Know-JS/tree/master/scope%20%26%20closures#you-dont-know-js-scope--closures) full chapter.

Cheers

**Comment by alvaropinot** [comment]
Wow @juliomatcom ❤️ to see you around!! :D

**Comment by juliomatcom** [comment]
haha I'm always looking :sunglasses: :v:
