### ISSUE TITLE
curry/composition🍆

### ISSUE THREAD

**Issue by lluissuros** [lbdjs/sessions#3]

**Comment by lluissuros** [comment]
I found this interesting:
https://medium.com/javascript-scene/master-the-javascript-interview-what-is-function-composition-20dfb109a1a0

**Comment by alvaropinot** [comment]
Yep Eric Elliot master the javascript interview series is awesome, follow the links, totally worth it :)

**Comment by alvaropinot** [comment]
this will be part of #4, but we can reopen this for doing more specific exercises.
